<a href="https://colab.research.google.com/github/MaltonLeo/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [10]:
import pandas as pd

In [8]:
print(pd.__version__)

2.2.2

In [15]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford","Ferrari","Dodge","Bugatti"],
    'counts': [3, 7, 2, 4, 8, 6]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Ferrari       4
4    Dodge       8
5  Bugatti       6

In [18]:
df.head() #default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Ferrari       4
4    Dodge       8

In [19]:
df.tail() #oxiridan  sanaydi default holatda 5 ta qator ko'rsatadi

      cars  counts
1    Volvo       7
2     Ford       2
3  Ferrari       4
4    Dodge       8
5  Bugatti       6

In [20]:
df.shape

(6, 2)

In [21]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [22]:
df.dtypes

cars      object
counts     int64
dtype: object

In [24]:
df.describe() #numerical columns only

         counts
count  6.000000
mean   5.000000
std    2.366432
min    2.000000
25%    3.250000
50%    5.000000
75%    6.750000
max    8.000000

In [26]:
df.iloc[1:4] # rowlarni select qilganda ularni columni bilan ko'rsatadi bu misolda 1 dan 3 gacha qatorlarni ko'rsatadi

      cars  counts
1    Volvo       7
2     Ford       2
3  Ferrari       4

In [27]:
df.iloc[2:] #bu yuqoridagi misolni boshqacharoq turi ya'ni 2 chi elementdan boshlab oxirigacha ko'rsatadi

      cars  counts
2     Ford       2
3  Ferrari       4
4    Dodge       8
5  Bugatti       6

In [28]:
df.loc[2:5, "cars"] # bu bizga ham rowlardan ham labellardan bir vaqtda foydalanib datani ko'rish imkonini beradi

2       Ford
3    Ferrari
4      Dodge
5    Bugatti
Name: cars, dtype: object

In [29]:
df[df["counts"]>3] # biz kiritgan label va shart bo'yicha datalarni ko'rish imkonini beradi

      cars  counts
1    Volvo       7
3  Ferrari       4
4    Dodge       8
5  Bugatti       6

In [30]:
df[df["cars"]=="Bugatti"] # string holatda Bugatti ga teng qiymatni olib keldi yuqoridagi misolni boshqa shart bilan tekshirdik

      cars  counts
5  Bugatti       6

In [31]:
df.mean(numeric_only=True) # qiymatlardagi raqamlarning o'rtacha qiymatini ko'rsatadi

counts    5.0
dtype: float64

In [32]:
df.counts.mean() # bu yuqoridagi o'tacha qiymat chiqarishning 2-usuli

np.float64(5.0)

In [33]:
df.sum() # barcha qiymatlar yig'indisini beradi

cars      BMWVolvoFordFerrariDodgeBugatti
counts                                 30
dtype: object

In [34]:
df.min() # minimum qiymatni beradi

cars      BMW
counts      2
dtype: object

In [35]:
df.max() # maximum qiymatni beradi

cars      Volvo
counts        8
dtype: object

In [36]:
df.median(numeric_only=True) #o'rtacha qiymatni hisoblab beradi

counts    5.0
dtype: float64

In [37]:
df.count() #null value larni qidiradi va null bo'lsa chiqaradi bo'lmasa bor ma'lumotlarni qaytaradi

cars      6
counts    6
dtype: int64

In [38]:
df.std(numeric_only=True) # standart deviation ni ko'rsatadi

counts    2.366432
dtype: float64

In [39]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)

print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [41]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [42]:
df_missing.dropna() # bunda qaysi qatorda cars yoki countsdan birortasini qiymati bo'lmasa o'chirib tashlaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [43]:
df_missing.dropna(how="all") # bunda qaysi qatorda cars yoki countsdan ikkitasini ham qiymati bo'lmasa o'chirib tashlaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [44]:
df_missing.dropna(axis=1) # bunda qaysi columnda birorta qiymati bo'lmasa o'sha columnni o'chirib tashlaydi

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [45]:
df_missing.dropna(subset="counts") # bunda counts bo'yicha qaysi qatorda qiymati bo'lmasa o'sha qatorni o'chirib tashlaydi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0

In [47]:
df_missing.fillna({"cars":"unknown","counts":0}) # bu datalari yo'q bo'lgan joylarni biz kiritgan ma'lumot bilan almashtirib ko'rsatadi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [51]:
df = pd.read_csv("Titanic-Dataset.csv")
df.head(10)
# df = pd.read_excel("Titanic-Dataset.xlsx") bu excel fileni o'qish uchun
# df = pd.read_json("Titanic-Dataset.json") bu json fileni o'qish uchun

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [52]:
df.to_excel("output.xlsx") # bu yuqoridagi filemizni xlsx ga output nomi bilan export qilib beradi

In [55]:
df = pd.read_excel("output.xlsx")
df.tail(10)

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
881,881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#Series => 1D arraylar bilan ishlaydi

In [56]:
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [57]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']