<a href="https://colab.research.google.com/github/MaltonLeo/ai_foundation/blob/main/students_performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("StudentsPerformance.csv")
print("Dataset shape (rows, columns):", df.shape)
print("Column name:", df.columns.tolist)

print("First 5 rows of the dataset:")
print(df.head())

print("Data types and null info:")
print(df.info())

Dataset shape (rows, columns): (2392, 15)
Column name: <bound method IndexOpsMixin.tolist of Index(['StudentID', 'Age', 'Gender', 'Ethnicity', 'ParentalEducation',
       'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport',
       'Extracurricular', 'Sports', 'Music', 'Volunteering', 'GPA',
       'GradeClass'],
      dtype='object')>
First 5 rows of the dataset:
   StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723
1       1002   18       0          0                  1        15.408756
2       1003   15       0          2                  3         4.210570
3       1004   17       1          0                  3        10.028829
4       1005   17       1          0                  2         4.672495

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1
1         0         0                1                0       0      0
2        26         0                2                0       0      0
3        14         0                3                1       0      0
4        17         1                3                0       0      0

   Volunteering       GPA  GradeClass
0             0  2.929196         2.0
1             0  3.042915         1.0
2             0  0.112602         4.0
3             0  2.054218         3.0
4             0  1.288061         4.0
Data types and null info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   StudentID          2392 non-null   int64
 1   Age                2392 non-null   int64
 2   Gender             2392 non-null   int64
 3   Ethnicity          2392 non-null   int64
 4   ParentalEducation  2392 non-null   int64
 5   StudyTimeWeekly    2392 non-null   float64
 6   Absences           2392 non-null   int64
 7   Tutoring           2392 non-null   int64
 8   ParentalSupport    2392 non-null   int64
 9   Extracurricular    2392 non-null   int64
 10  Sports             2392 non-null   int64
 11  Music              2392 non-null   int64
 12  Volunteering       2392 non-null   int64
 13  GPA                2392 non-null   float64
 14  GradeClass         2392 non-null   float64
dtypes: float64(3), int64(12)
memory usage: 280.4 KB
None

In [10]:
print("Average score by columns:")
df[["Sports", "Music", "Volunteering"]].mean()

Average score by columns:

Sports          0.303512
Music           0.196906
Volunteering    0.157191
dtype: float64

In [11]:
print("Maximum score by columns:")
df[["Sports", "Music", "Volunteering"]].max()

Average score by columns:

Sports          1
Music           1
Volunteering    1
dtype: int64

In [13]:
print("Minimum score by columns:")
df[["Sports", "Music", "Volunteering"]].min()

Minimum score by columns:

Sports          0
Music           0
Volunteering    0
dtype: int64

In [14]:
# Correlation
print("Correlation:")
df[["Sports", "Music", "Volunteering"]].corr()

Correlation:

                Sports     Music  Volunteering
Sports        1.000000 -0.020474     -0.002799
Music        -0.020474  1.000000      0.017224
Volunteering -0.002799  0.017224      1.000000

In [15]:
df["total score"] = df[["Sports", "Music", "Volunteering"]].sum(axis=1)
df["average score"] = df["total score"] / 3
df["passed"] = np.where(df["average score"] >= 50, "Yes", "No")

print("New columns preview (total, average, passed):")
print(df[["total score", "average score", "passed"]].head())

New columns preview (total, average, passed):
   total score  average score passed
0            1       0.333333     No
1            0       0.000000     No
2            0       0.000000     No
3            0       0.000000     No
4            0       0.000000     No

In [22]:
test_prep_group = df.groupby('StudyTimeWeekly')[["Sports", "Music", "Volunteering"]].mean()
print("student score by test preperation course:")
print(test_prep_group)

# Gender-based average
gender_avg = df.groupby("Gender")[["Sports", "Music", "Volunteering"]].mean()
print("Average score by gender:")
print(gender_avg)

# Who passed vs failed
pass_rate = df["passed"].value_counts(normalize=True) * 100
print("Pass rate:\n", pass_rate)

student score by test preperation course:
                 Sports  Music  Volunteering
StudyTimeWeekly
0.001057            1.0    0.0           0.0
0.004859            0.0    0.0           0.0
0.008031            0.0    1.0           0.0
0.008206            0.0    0.0           0.0
0.014337            0.0    0.0           0.0
...                 ...    ...           ...
19.939810           1.0    0.0           1.0
19.948459           0.0    0.0           0.0
19.968425           0.0    0.0           0.0
19.972346           0.0    0.0           0.0
19.978094           0.0    0.0           0.0

[2392 rows x 3 columns]
Average score by gender:
          Sports     Music  Volunteering
Gender
0       0.307692  0.194017      0.157265
1       0.299509  0.199673      0.157119
Pass rate:
 passed
No    100.0
Name: proportion, dtype: float64

In [25]:
# Convert scores to Numpy array
scores = df[["Sports", "Music", "Volunteering"]].values

# Mean, Std Deviation
print("Numpy Mean:", np.mean(scores, axis=0))
print("Numpy Std:", np.std(scores, axis=0))

# Z-score (normalize)
z_score = (scores - np.mean(scores, axis=0)) / np.std(scores, axis=0)
print("Z-scores (normalized numbers)")
print(z_score[:5])
# Average 0
# Negative -
# Positive +

Numpy Mean: [0.30351171 0.19690635 0.15719064]
Numpy Std: [0.45977424 0.39766096 0.36398041]
Z-scores (normalized numbers)
[[-0.66013204  2.01954358 -0.43186565]
 [-0.66013204 -0.49516139 -0.43186565]
 [-0.66013204 -0.49516139 -0.43186565]
 [-0.66013204 -0.49516139 -0.43186565]
 [-0.66013204 -0.49516139 -0.43186565]]

In [26]:
# How many students scored above 90 average?
top_scorers = df[df["average score"] >=90]
print("Top scored student above 90:", len(top_scorers))

# How many failed?
failed = df[df["passed"] == "No"]
print("Failed from exam:", len(failed))

Top scored student above 90: 0
Failed from exam: 2392